app = "scrapbook-core"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  DEBUG = "false"

[mounts]
  source = "data"
  destination = "/usr/src/app/data"

[[vm]]
  cpu_kind = "shared"
  memory_mb = 1024
  count = 1

[scheduled_jobs]
  [[scheduled_jobs.jobs]]
    name = "run-scraper"
    schedule = "@daily"
    command = "node scripts/index.mjs --all"
