app = "scrapbook-core"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[mounts]
  source = "data"
  destination = "/usr/src/app/data"

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 8192
  swap_size_mb = 8192

[processes]
  app = "node scripts/index.mjs --all"

[[services]]
  processes = ["app"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[scheduled_jobs]
  [[scheduled_jobs.jobs]]
    name = "run-scraper"
    schedule = "@daily"
    command = "node scripts/index.mjs --all"
