import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
dotenv.config();

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY,
);

(async () => {
  // Get specific scraps that were recently processed
  const { data, error } = await supabase
    .from("scraps")
    .select("id, title, summary, tags")
    .in("id", [
      "pinboard-5272c798103d65dac3684c1d01664c5b",  // FPV goggles
      "pinboard-c85f7af9c3f4095a30942ed9fc2c5ff8",  // Gaza polling
      "pinboard-a75fc1fa91622c74d92cb713b0851ad7",   // Shock poll
    ]);

  if (error) {
    console.error("Error:", error);
    return;
  }

  console.log("📝 ACTUAL SUMMARIES GENERATED BY GEMINI FLASH:");
  console.log("=".repeat(80));

  data.forEach((scrap, i) => {
    console.log(`\n📌 ITEM ${i+1}: ${scrap.title?.slice(0, 80)}`);
    console.log("ID: " + scrap.id);
    console.log("TAGS: " + (scrap.tags?.join(", ") || "none"));
    console.log("\nSUMMARY:");
    console.log("-".repeat(40));

    // Show the actual summary with bullet points
    if (scrap.summary) {
      const lines = scrap.summary.split("\n");
      lines.forEach(line => {
        if (line.trim().startsWith("•")) {
          console.log(line);
        } else if (line.trim()) {
          console.log(`[INTRO] ${line}`);
        }
      });

      console.log(`\n[LENGTH: ${scrap.summary.length} chars]`);
    } else {
      console.log("[NO SUMMARY]");
    }

    console.log("\n" + "=".repeat(80));
  });
})();
