export const SEMANTIC_PREDICATES = [
  {
    id: 'WORKS_FOR',
    description: 'A person works for or holds a role within an organization.',
    subjectTypes: ['Person'],
    objectTypes: ['Organization'],
    aliases: ['EMPLOYED_BY', 'EMPLOYEE_OF', 'STAFF_AT'],
  },
  {
    id: 'LEADS',
    description: 'A person leads, heads, chairs, or directs an organization, project, or movement.',
    subjectTypes: ['Person'],
    objectTypes: ['Organization', 'Project', 'Movement'],
    aliases: ['HEADS', 'DIRECTS', 'CHAIRS', 'RUNS'],
  },
  {
    id: 'FOUNDED',
    description: 'A person founded an organization, project, movement, tool, model, or artwork.',
    subjectTypes: ['Person'],
    objectTypes: ['Organization', 'Project', 'Movement', 'Tool', 'Model', 'Artwork'],
    aliases: ['FOUNDER_OF', 'CO_FOUNDED', 'COFOUNDED'],
  },
  {
    id: 'MEMBER_OF',
    description: 'A person is a member of an organization, project, or movement.',
    subjectTypes: ['Person'],
    objectTypes: ['Organization', 'Project', 'Movement'],
    aliases: ['BELONGS_TO'],
  },
  {
    id: 'ADVISES',
    description: 'A person advises an organization, project, or movement.',
    subjectTypes: ['Person'],
    objectTypes: ['Organization', 'Project', 'Movement'],
    aliases: ['ADVISOR_TO', 'CONSULTS_FOR'],
  },
  {
    id: 'FUNDS',
    description: 'A person or organization funds another entity.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Organization', 'Project', 'Movement', 'Artwork', 'Dataset', 'Tool', 'Model'],
    aliases: [],
    inverseAliases: ['FUNDED_BY', 'BACKED_BY', 'SUPPORTED_BY', 'SPONSORED_BY'],
  },
  {
    id: 'DONATES_TO',
    description: 'A person or organization donates to another entity.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Organization', 'Project', 'Movement', 'Artwork'],
    aliases: ['CONTRIBUTES_TO', 'GIVES_TO'],
    inverseAliases: ['RECEIVED_DONATION_FROM'],
  },
  {
    id: 'INVESTS_IN',
    description: 'A person or organization invests in another entity.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Organization', 'Project', 'Tool', 'Model', 'Dataset'],
    aliases: ['INVESTED_INTO'],
    inverseAliases: ['INVESTMENT_FROM', 'RAISED_FROM'],
  },
  {
    id: 'CONTRACTS_WITH',
    description: 'An organization or project contracts with another organization.',
    subjectTypes: ['Organization', 'Project'],
    objectTypes: ['Organization', 'Project'],
    aliases: ['SIGNED_CONTRACT_WITH', 'IN_CONTRACT_WITH'],
  },
  {
    id: 'PARTNERS_WITH',
    description: 'An organization, project, or movement partners with another organization, project, or movement.',
    subjectTypes: ['Organization', 'Project', 'Movement'],
    objectTypes: ['Organization', 'Project', 'Movement'],
    aliases: ['COLLABORATES_WITH'],
  },
  {
    id: 'OWNS',
    description: 'A person or organization owns another entity.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Organization', 'Tool', 'Model', 'Dataset', 'Artwork', 'Project'],
    aliases: ['ACQUIRED', 'PURCHASED'],
    inverseAliases: ['OWNED_BY', 'ACQUIRED_BY'],
  },
  {
    id: 'CONTROLS',
    description: 'A person or organization controls another entity.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Organization', 'Project', 'Tool', 'Model', 'Dataset'],
    aliases: ['OVERSEES', 'MANAGES'],
    inverseAliases: ['CONTROLLED_BY'],
  },
  {
    id: 'OPERATES',
    description: 'A person or organization operates a project, tool, dataset, or location.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Project', 'Tool', 'Dataset', 'Location'],
    aliases: ['RUNS', 'MAINTAINS'],
    inverseAliases: ['OPERATED_BY'],
  },
  {
    id: 'DEVELOPS',
    description: 'A person or organization develops a tool, model, dataset, or project.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Tool', 'Model', 'Dataset', 'Project'],
    aliases: ['BUILDS'],
    inverseAliases: ['DEVELOPED_BY', 'BUILT_BY'],
  },
  {
    id: 'CREATED',
    description: 'A person or organization created or authored an artwork.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Artwork'],
    aliases: ['CREATES', 'AUTHORED', 'MADE'],
    inverseAliases: ['CREATED_BY', 'AUTHORED_BY'],
  },
  {
    id: 'USES',
    description: 'An entity uses a tool, model, or dataset.',
    subjectTypes: ['Person', 'Organization', 'Project', 'Tool', 'Model'],
    objectTypes: ['Tool', 'Model', 'Dataset'],
    aliases: ['USED'],
    inverseAliases: ['USED_BY'],
  },
  {
    id: 'INTEGRATES_WITH',
    description: 'A tool or model integrates with another tool or model.',
    subjectTypes: ['Tool', 'Model'],
    objectTypes: ['Tool', 'Model'],
    aliases: ['CONNECTS_TO'],
  },
  {
    id: 'HOSTED_ON',
    description: 'A tool, model, or dataset is hosted on an organization or tool platform.',
    subjectTypes: ['Tool', 'Model', 'Dataset'],
    objectTypes: ['Organization', 'Tool'],
    aliases: [],
  },
  {
    id: 'LOCATED_IN',
    description: 'An entity is located in a place.',
    subjectTypes: ['Person', 'Organization', 'Project', 'Movement', 'Artwork', 'Tool', 'Model', 'Dataset', 'Location'],
    objectTypes: ['Location'],
    aliases: ['BASED_IN', 'HEADQUARTERED_IN', 'OPERATES_IN', 'REGISTERED_IN'],
  },
  {
    id: 'INVESTIGATES',
    description: 'A person or organization investigates another entity.',
    subjectTypes: ['Person', 'Organization', 'Project'],
    objectTypes: ['Person', 'Organization', 'Project', 'Movement', 'Dataset', 'Tool', 'Model', 'Location'],
    aliases: ['PROBES'],
  },
  {
    id: 'SUES',
    description: 'A person or organization sues another person or organization.',
    subjectTypes: ['Person', 'Organization'],
    objectTypes: ['Person', 'Organization'],
    aliases: ['FILES_SUIT_AGAINST'],
    inverseAliases: ['SUED_BY'],
  },
  {
    id: 'TARGETS',
    description: 'A person or organization targets another entity.',
    subjectTypes: ['Person', 'Organization', 'Project'],
    objectTypes: ['Person', 'Organization', 'Project', 'Movement', 'Location'],
    aliases: [],
  },
  {
    id: 'APPROVES',
    description: 'An organization approves another entity.',
    subjectTypes: ['Organization'],
    objectTypes: ['Organization', 'Project', 'Tool', 'Model', 'Dataset'],
    aliases: ['AUTHORIZED'],
    inverseAliases: ['APPROVED_BY'],
  },
  {
    id: 'BANS',
    description: 'An organization bans another entity.',
    subjectTypes: ['Organization'],
    objectTypes: ['Organization', 'Tool', 'Model', 'Project', 'Movement'],
    aliases: ['RESTRICTS'],
    inverseAliases: ['BANNED_BY'],
  },
  {
    id: 'QUOTES',
    description: 'A document-like source quotes a person or organization. Use sparingly in semantic extraction.',
    subjectTypes: ['Organization', 'Project'],
    objectTypes: ['Person', 'Organization'],
    aliases: [],
  },
]
